name: Test Suite

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo build;
      - run: cargo test;
